[bot]
client-id = "<discord client id>"
client-secret = "<discord client secret>"
redirect-uri = "<discord callback url>"
official-server-id = "<official discord server id>"

[server]
host = "0.0.0.0"
port = 3000

# please generate secret key and paste for gen-secret.sh script.
secret = ""

[database]
host = "127.0.0.1"
port = 3306
name = "neko-engine"
username = "<mariadb_username>"
password = "<mariadb_password>"

[gemini]
token = ""
